### ISSUE TITLE
Is Optifine going to be added?

### ISSUE THREAD

**Issue by pokeball99** [BigDaddyUS/BigDaddy#7]
im asking this because you will get it asked alot to put it in if u don't,just take a look at this, https://github.com/Wurst-Imperium/Wurst-Client/issues?utf8=%E2%9C%93&q=Optifine+label%3Aduplicate

**Comment by BigDaddyUS** [comment]
It's added. It's just not implemented  yet. It will be on the next release. A lot of things will be added next update.

**Comment by pokeball99** [comment]
nice
